version: '3.8'
services:
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 54321:5432
  app:
    build:
      context: .
      target: build
      args:
        MIX_ENV: prod
    env_file: .env
    ports:
      - "4000:4000"
      - "4001:4001"
    depends_on:
    - db
    volumes:
      - code:/app
volumes:
  code: null
x-mutagen:
  sync:
    defaults:
      ignore:
        vcs: true
    code:
      alpha: "."
      beta: "volume://code"
      mode: "two-way-resolved"

